;<?php
;die();
;/*
[STRING]
	ABOUT					= "Περί"
	ADMIN					= "Διαχείριση"
	AUTHOR					= "Δημιουργός"
	CREATE					= "Δημιουργία"
	DATABASES				= "Doodles"
	DATE					= "Ημερομηνία"
	DATE_ADD				= "Προσθήκη ημερομηνίας"
	DATE_LIST				= "Λίστα διαθέσιμων ημερομηνιών"
	DATES					= "Ημερομηνίες"
	DELETE					= "Διαγραφή"
	DOODLE_DATA				= "Βασικά στοιχεία"
	DOWNLOAD				= "Κατέβασμα"
	DURATION				= "Διάρκεια"
	ERROR_FILE_READ			= "Δεν ήταν δυνατή η ανάγνωση του αρχείου"
	ERROR_FILE_DELETE		= "Δεν ήταν δυνατή η διαγραφή του αρχείου"
	ERROR_FILE_MISSING		= "Δεν υπάρχει το συγκεκριμένο αρχείο"
	ERROR_FILE_SAVE			= "Δεν ήταν δυνατή η αποθήκευση του αρχείου"
	ERROR_FILE_STRUCTURE	= "Η δομή του αρχείου δεν είναι σωστή, χρησιμοποιείστε το πρότυπο"
	ERROR_PIN				= "Λάθος PIN και PIN διαχειριστή"
	ERROR_PIN_EMPTY			= "Το PIN μέσα στο αρχείο είναι κενό"
	ERROR_PIN_DIFFERENT		= "Το παλιό PIN με το νέο είναι διαφορετικό"
	ERROR_PIN_MISSING		= "Δεν υπάρχει PIN μέσα στο αρχείο"
	ERROR_PIN_EXISTS		= "Υπάρχει ήδη αποθηκευμένο κουίζ με το ίδιο PIN"
	FILE_DELETED			= "Το αρχείο διαγράφηκε με επιτυχία"
	FILE_UPDATE				= "Το αρχείο ενημερώθηκε με επιτυχία"
	FILE_UPLOAD				= "Το αρχείο αποθηκεύτηκε με επιτυχία"
	GENERATE				= "Παραγωγή"
	HOME					= "Αρχική σελίδα"
	HELP					= "Βοήθεια"
	IP						= "IP"
	INSTRUCTIONS			= "Οδηγίες"
	LANGUAGE				= "Γλώσσα"
	MINUTES					= "Λεπτά"
	PARTICIPANT				= "Συμμετέχων"
	PIN_QUIZ				= "PIN"
	PIN_QUIZ_ADMIN			= "PIN διαχειριστή"
	PIN_QUIZ_HELP			= "Εισάγετε το PIN της συνάντησης"
	RESULTS					= "Αποτελέσματα"
	SUBMIT					= "Υποβολή"
	TITLE					= "Τίτλος"
	TEMPLATE				= "Πρότυπο"
	UPDATE					= "Ενημέρωση"
	UNKNOWN					= "Άγνωστος"
	VERSION					= "Έκδοση"
[DAYS]
    Monday    				= "Δευτέρα"
    Tuesday					= "Τρίτη"
    Wednesday				= "Τετάρτη"
    Thursday				= "Πέμπτη"
    Friday					= "Παρασκευή"
    Saturday				= "Σάββατο"
    Sunday					= "Κυριακή"
;*/
;?>
